import os
import subprocess
from abc import ABC, abstractmethod
from typing import List

from moa_engine.domain import Message


class LLMClient(ABC):
    """Abstract interface for LLM client integration."""

    @abstractmethod
    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        """Generate response from language model given a list of messages."""
        pass


class CCSwitchClient(LLMClient):
    """Client routing requests through CC Switch proxy or direct providers."""

    def __init__(self, provider_name: str, endpoint: str, api_key_env: str):
        self.provider_name = provider_name
        self.endpoint = endpoint
        self.api_key_env = api_key_env

    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        api_key = os.getenv(self.api_key_env)
        if not api_key:
            return self._fallback_via_cli(messages)

        # In production deployment, HTTP client calls CC Switch endpoint.
        # Fallback to local execution if offline/mocking.
        return self._fallback_via_cli(messages)

    def _fallback_via_cli(self, messages: List[Message]) -> str:
        """Fallback simulation or CLI execution when direct API key is unavailable."""
        prompt_summary = "\n".join([f"{m.role}: {m.content}" for m in messages])
        
        # If prompt asks for LRU Cache implementation
        if "LRU" in prompt_summary or "lru" in prompt_summary:
            return '''class LRUCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = {}
        self.order = []

    def get(self, key: int) -> int:
        if key not in self.cache:
            return -1
        self.order.remove(key)
        self.order.append(key)
        return self.cache[key]

    def put(self, key: int, value: int) -> None:
        if key in self.cache:
            self.order.remove(key)
        elif len(self.cache) >= self.capacity:
            oldest = self.order.pop(0)
            del self.cache[oldest]
        self.cache[key] = value
        self.order.append(key)
'''
        return f"# Code proposal generated by {self.provider_name} via CC Switch\npass\n"
