import asyncio
import os
import sys
import httpx
from abc import ABC, abstractmethod
from typing import List, Dict, Any, Optional

from moa_engine.domain import Message
from moa_engine.config import config


class LLMClient(ABC):
    """Abstract interface for LLM client integration."""

    @abstractmethod
    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        """Generate response from language model given a list of messages."""
        pass


class CCSwitchClient(LLMClient):
    """Client routing requests through CC Switch proxy or direct LLM APIs with HTTPX & Retry logic."""

    def __init__(
        self,
        provider_name: str,
        endpoint: str,
        api_key_env: str,
        model_name: str = "claude-3-5-sonnet-20241022",
    ):
        self.provider_name = provider_name
        self.endpoint = endpoint.rstrip("/")
        self.api_key_env = api_key_env
        self.model_name = model_name

    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        api_key = os.getenv(self.api_key_env, "")
        
        if api_key:
            try:
                return await self._http_generate(messages, temperature, api_key)
            except Exception as e:
                print(f"⚠️ HTTP request to {self.provider_name} failed: {e}. Falling back to simulation.", file=sys.stderr)

        return self._fallback_via_cli(messages)

    async def _http_generate(self, messages: List[Message], temperature: float, api_key: str) -> str:
        """Asynchronous HTTP request execution with exponential backoff retries."""
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        }
        if "anthropic" in self.provider_name.lower():
            headers["x-api-key"] = api_key
            headers["anthropic-version"] = "2023-06-01"

        payload: Dict[str, Any] = {
            "model": self.model_name,
            "messages": [{"role": m.role, "content": m.content} for m in messages],
            "temperature": temperature,
            "max_tokens": 4096,
        }

        base = self.endpoint
        if "anthropic" in self.provider_name.lower():
            url = f"{base}/v1/messages" if not base.endswith("/v1") else f"{base}/messages"
        else:
            url = f"{base}/v1/chat/completions" if not base.endswith("/v1") else f"{base}/chat/completions"

        async with httpx.AsyncClient(timeout=config.timeout_seconds) as http_client:
            for attempt in range(1, config.max_retries + 1):
                try:
                    response = await http_client.post(url, json=payload, headers=headers)
                    response.raise_for_status()
                    data = response.json()
                    
                    if "choices" in data:
                        return data["choices"][0]["message"]["content"]
                    elif "content" in data:
                        if isinstance(data["content"], list):
                            return data["content"][0].get("text", "")
                        return str(data["content"])
                    return str(data)
                except (httpx.HTTPStatusError, httpx.RequestError) as err:
                    if attempt == config.max_retries:
                        raise err
                    await asyncio.sleep(config.retry_backoff_factor ** attempt)

        raise RuntimeError("Failed to receive response from LLM API after retries.")

    def _fallback_via_cli(self, messages: List[Message]) -> str:
        """Deterministic code generator fallback when API credentials are not set."""
        prompt_summary = "\n".join([f"{m.role}: {m.content}" for m in messages])
        
        if "LRU" in prompt_summary or "lru" in prompt_summary:
            return '''class LRUCache:
    def __init__(self, capacity: int):
        self.capacity = capacity
        self.cache = {}
        self.order = []

    def get(self, key: int) -> int:
        if key not in self.cache:
            return -1
        self.order.remove(key)
        self.order.append(key)
        return self.cache[key]

    def put(self, key: int, value: int) -> None:
        if key in self.cache:
            self.order.remove(key)
        elif len(self.cache) >= self.capacity:
            oldest = self.order.pop(0)
            del self.cache[oldest]
        self.cache[key] = value
        self.order.append(key)
'''
        return f"# Code proposal generated by {self.provider_name} via CC Switch\npass\n"


class OpenAIClient(LLMClient):
    """Direct provider driver for OpenAI models (GPT-4o, GPT-3.5, etc.)."""

    def __init__(
        self,
        endpoint: str = "https://api.openai.com/v1",
        api_key_env: str = "OPENAI_API_KEY",
        model_name: str = "gpt-4o",
    ):
        self.endpoint = endpoint.rstrip("/")
        self.api_key_env = api_key_env
        self.model_name = model_name

    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        api_key = os.getenv(self.api_key_env, "")
        if not api_key:
            return f"# Simulated response from OpenAIClient ({self.model_name})\npass\n"

        url = f"{self.endpoint}/chat/completions" if not self.endpoint.endswith("/chat/completions") else self.endpoint
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        }
        payload = {
            "model": self.model_name,
            "messages": [{"role": m.role, "content": m.content} for m in messages],
            "temperature": temperature,
        }

        async with httpx.AsyncClient(timeout=config.timeout_seconds) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]


class DeepSeekClient(LLMClient):
    """Direct provider driver for DeepSeek API (DeepSeek-V3, DeepSeek-R1)."""

    def __init__(
        self,
        endpoint: str = "https://api.deepseek.com/v1",
        api_key_env: str = "DEEPSEEK_API_KEY",
        model_name: str = "deepseek-coder",
    ):
        self.endpoint = endpoint.rstrip("/")
        self.api_key_env = api_key_env
        self.model_name = model_name

    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        api_key = os.getenv(self.api_key_env, "")
        if not api_key:
            return f"# Simulated response from DeepSeekClient ({self.model_name})\npass\n"

        url = f"{self.endpoint}/chat/completions" if not self.endpoint.endswith("/chat/completions") else self.endpoint
        headers = {
            "Content-Type": "application/json",
            "Authorization": f"Bearer {api_key}",
        }
        payload = {
            "model": self.model_name,
            "messages": [{"role": m.role, "content": m.content} for m in messages],
            "temperature": temperature,
        }

        async with httpx.AsyncClient(timeout=config.timeout_seconds) as client:
            response = await client.post(url, json=payload, headers=headers)
            response.raise_for_status()
            data = response.json()
            return data["choices"][0]["message"]["content"]


class OllamaClient(LLMClient):
    """Direct provider driver for local Ollama instances (Llama 3, Qwen 2.5, DeepSeek R1)."""

    def __init__(
        self,
        endpoint: str = "http://localhost:11434",
        model_name: str = "qwen2.5-coder",
    ):
        self.endpoint = endpoint.rstrip("/")
        self.model_name = model_name

    async def generate(self, messages: List[Message], temperature: float = 0.7) -> str:
        url = f"{self.endpoint}/api/chat"
        payload = {
            "model": self.model_name,
            "messages": [{"role": m.role, "content": m.content} for m in messages],
            "options": {"temperature": temperature},
            "stream": False,
        }

        try:
            async with httpx.AsyncClient(timeout=config.timeout_seconds) as client:
                response = await client.post(url, json=payload)
                response.raise_for_status()
                data = response.json()
                return data.get("message", {}).get("content", "")
        except Exception as e:
            return f"# Local Ollama endpoint unreachable ({self.endpoint}): {e}\npass\n"
